language: python
python:
  - "3.5"
install:
  - pip install --upgrade pip
  - "pip install .[dev]"
before_script:
  - pip freeze
script:
  - make linter
  - nosetests
  - python -m astexport --help
  - echo "x = 5" | python -m astexport --pretty
